### ISSUE TITLE
Component lifecycle hooks

### ISSUE THREAD

**Issue by oginskis** [agilestacks/hub#13]
As a DevOps engineer, I assemble stacks from generic components. Sometimes, before or after I deploy a component, I need to perform an action that extends the component and often is environment or context-specific.

#### Responsibilities of the generic Grafana component:
- Template `values.yaml` file of the corresponding Helm chart
- Run `helm install` to deploy the component to Kubernetes
- Run `helm delete` to undeploy the component from Kubernetes

#### Responsibilities of the lifecycle hooks:
- Before deploy
   - Prepare Kubernetes context for deployment (the way how to retrieve the context differs from cloud to cloud)

- After deploy
   - Deploy GCP Support data sources and dashboards to Grafana 

- Before undeploy
   - Prepare Kubernetes context for deployment (the way how to retrieve the context differs from cloud to cloud)

This approach allows keeping Grafana component KISS, if-less programming, and no cloud or env-specific code in the body of the component.

Agreed on:

```
- name: mgmt-grafana
  source:
    dir: components/grafana
    git:
      remote: https://github.com/agilestacks/google-components.git
      subDir: grafana
  hooks:
  - brief: Set GKE context
    file: .hub/gke-context
    triggers:
    - pre-*deploy
  - brief: Deploy datasource
    file: .hub/datasource
    triggers:
    - post-deploy      
  - brief: Deploy dashboard
    file: .hub/dashboard
    triggers:
    - post-deploy    
```

To do:

- [x] document hub CLI local setup
- [x] development
- [ ] unit test
- [x] release
- [x] on error fail flag
- [x] print env vars of hooks
- [x] if file not found - fail
