### ISSUE TITLE
Parametrise working dir for hook

### ISSUE THREAD

**Issue by akranga** [agilestacks/hub#54]
Related to #23. User wants to parametrise working directory for hook execution....

Proposing following format:

1. When user defines as the following 

```yaml
components:
- name: authn
  # ...
  hooks:
  - file: bin/authn-post-deploy
    triggers: [post-deploy]
```

Then the `bin/authn-post-deploy` executed from the directory of `authn` component

2. When user defines a `workDir` argument as the following

```yaml
hooks:
- file: bin/authn-post-deploy
  triggers: [post-deploy]
  workDir: .
```

...then the `bin/authn-post-deploy` script is executed from the same directory as `hub.yaml`, same as the value of `$HUB_BASE_DIR`

3. When user defines a `worker` argument as the following

```yaml
hooks:
- file: bin/authn-post-deploy
  triggers: [post-deploy]
  workDir: bin
```

...then the `bin/authn-post-deploy` script is executed from the same directory as  `bin/authn-post-deploy`, the same place as `$HUB_BASE_DIR/bin`
