### ISSUE TITLE
Group parameters by component

### ISSUE THREAD

**Issue by akranga** [agilestacks/hub#58]
Today hub supports following notation (see below) that only allow to group parameters prefixed by another parameter. Yet we are getting more and more parameters that are rather generic. 

```yaml
parameters:
- name: kubernetes
  component: foo
  parameters:
  - name: namespace
    value: kube-system
    # ...
- name: ingress
  component: foo
  parameters:
  - name: hosts
    value: foo.example.com
    # ...
```

Proposed form brings more compact form of the same

```yaml
parameters:
- component: foo
   parameters:
   - name: kubernetes.namespace
     value: foo
   - name: ingres.hosts
     value: foo.example.com
- component: bar
   parameters:
   - name: kubernetes.namespace
     value: bar
   - name: ingres.hosts
     value: bar.example.com
```
