### ISSUE TITLE
Kubectl version requirement cannot be satisfied

### ISSUE THREAD

**Issue by TheRealSpaceShip** [agilestacks/hub#69]
Steps to reproduce:

1. Run `hubctl stack init` stack with `required: kubernetes`
2. Run `hubctl stack deploy` of this stack

**Actual result:**
Checking of `kubectl` version failed with the next message:

```
2023/09/20 14:57:42 WARN: `kubectl` version requirement cannot be satisfied: kubernetes: no version string found; update `kubectl` binary?
```

**Expected result:**
If the version of `kubectl` is equal to or newer than required then no warning message should be.

My version of `kubectl`

```shell
kubectl version --client -o=json
{
  "clientVersion": {
    "major": "1",
    "minor": "28",
    "gitVersion": "v1.28.1",
    "gitCommit": "8dc49c4b984b897d423aab4971090e1879eb4f23",
    "gitTreeState": "clean",
    "buildDate": "2023-08-24T11:16:29Z",
    "goVersion": "go1.20.7",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3"
}
```

Example of `hub.yaml` of stack

```yaml
kind: stack
version: 1

requires:
- kubernetes

extensions:
  configure:
  - kubernetes
  - env
  deploy:
    before:
    - kubernetes

components:
- name: cert-manager
  source:
    dir: components/cert-manager
    git:
      remote: https://github.com/epam/hub-kubeflow-components.git
      subDir: cert-manager
```
